export interface StoreConfig {
  allow_segmentation: boolean
  allow_labelling: boolean
  allow_owner_assignment: boolean
  default_capacity_unit: string
}

export interface StoreLocation {
  id: string
  org_id: string
  property_id: string
  name: string
  code: string
  label?: string
  description?: string
  location_type: 'store' | 'zone' | 'aisle' | 'rack' | 'bay' | 'level' | 'bin'
  parent_id?: string
  store_id?: string
  path: string
  depth: number
  sort_order: number
  capacity_value?: number
  capacity_unit: string
  current_occupancy: number
  occupancy_pct: number
  assigned_officer_id?: string
  assigned_officer_name?: string
  attributes: Record<string, unknown>
  status: 'active' | 'inactive' | 'maintenance'
  created_at: string
  updated_at: string
  children: StoreLocation[]
}

export interface StoreListResponse {
  stores: StoreLocation[]
  total: number
}

export interface StoreCapacitySummary {
  location_id: string
  location_name: string
  path: string
  capacity_value?: number
  capacity_unit: string
  current_occupancy: number
  occupancy_pct: number
  status: string
}

export interface StoreCreatePayload {
  name: string
  code?: string   // auto-generated by backend if omitted
  label?: string
  description?: string
  capacity_value?: number
  capacity_unit?: string
  assigned_officer_id?: string
  assigned_officer_name?: string
  attributes?: Record<string, unknown>
  sort_order?: number
}

export interface StoreLocationCreatePayload {
  name: string
  code?: string   // auto-generated by backend if omitted
  label?: string
  description?: string
  location_type: 'zone' | 'aisle' | 'rack' | 'bay' | 'level' | 'bin'
  parent_id?: string
  capacity_value?: number
  capacity_unit?: string
  assigned_officer_id?: string
  assigned_officer_name?: string
  attributes?: Record<string, unknown>
  sort_order?: number
}

export interface StoreLocationUpdatePayload {
  name?: string
  code?: string
  label?: string
  description?: string
  capacity_value?: number
  capacity_unit?: string
  assigned_officer_id?: string
  assigned_officer_name?: string
  attributes?: Record<string, unknown>
  sort_order?: number
  status?: string
}

export interface StoreConfigUpdatePayload {
  allow_segmentation?: boolean
  allow_labelling?: boolean
  allow_owner_assignment?: boolean
  default_capacity_unit?: string
}
