apiVersion: v1
kind: Service
metadata:
  name: pms-backend-service
  namespace: pms
spec:
  selector:
    app: pms-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
