"""
Trainer Service API — called from inside trainer code via ServiceClient.

Authentication: Bearer API key (generated by user via POST /api-keys).
All endpoints are read-only and scoped to the key owner's org.

Trainers call these via self.service_client("sk_..."):
    client = self.service_client("sk_xxx")
    df      = client.get_dataset("my-slug")
    models  = client.list_models()
    result  = client.run_inference("model-name", {"field": "value"})
"""
from __future__ import annotations

from typing import Any, Dict, Optional

import structlog
from fastapi import APIRouter, Depends, HTTPException, Header
from pydantic import BaseModel

from app.services.api_key_service import validate_key

router = APIRouter(prefix="/trainer-api", tags=["trainer-api"])
logger = structlog.get_logger(__name__)


# ── Auth dependency ────────────────────────────────────────────────────────────

async def _require_api_key(authorization: str = Header(...)):
    """Extract and validate Bearer API key; return the ApiKey record."""
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Authorization header must be 'Bearer <api_key>'")
    raw_key = authorization.removeprefix("Bearer ").strip()
    record = await validate_key(raw_key)
    if not record:
        raise HTTPException(status_code=401, detail="Invalid or expired API key")
    return record


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/me")
async def whoami(key=Depends(_require_api_key)):
    """Verify the key and return its metadata."""
    return {
        "owner_email": key.owner_email,
        "org_id": key.org_id,
        "name": key.name,
        "prefix": key.key_prefix,
        "usage_count": key.usage_count,
    }


@router.get("/datasets")
async def list_datasets(key=Depends(_require_api_key)):
    """List datasets belonging to this org."""
    from app.models.dataset import DatasetProfile
    org_id = key.org_id
    if not org_id:
        return []
    datasets = await DatasetProfile.find(
        {"org_id": org_id, "deleted_at": None}
    ).to_list()
    return [
        {
            "slug": d.slug,
            "name": d.name,
            "description": d.description,
            "row_count": d.row_count,
            "size_bytes": d.size_bytes,
            "created_at": d.created_at,
        }
        for d in datasets
    ]


@router.get("/datasets/{slug}/download")
async def download_dataset(slug: str, key=Depends(_require_api_key)):
    """
    Download dataset content.
    Returns {"rows": [...]} for tabular data or {"file_url": "..."} for file datasets.
    """
    from app.models.dataset import DatasetProfile
    org_id = key.org_id
    if not org_id:
        raise HTTPException(status_code=403, detail="API key has no org scope")
    dataset = await DatasetProfile.find_one({"org_id": org_id, "slug": slug, "deleted_at": None})
    if not dataset:
        raise HTTPException(status_code=404, detail=f"Dataset '{slug}' not found")

    # Tabular: return rows directly
    if dataset.rows:
        return {"slug": slug, "rows": dataset.rows, "row_count": len(dataset.rows)}

    # File-backed: return a presigned S3 URL
    if dataset.file_key:
        try:
            import aioboto3 as _aio
            from app.core.config import settings as _s
            s3_key = dataset.file_key
            session = _aio.Session()
            async with session.client(
                "s3",
                endpoint_url=_s.S3_ENDPOINT_URL,
                aws_access_key_id=_s.S3_ACCESS_KEY,
                aws_secret_access_key=_s.S3_SECRET_KEY,
                region_name=_s.S3_REGION,
            ) as s3:
                url: str = await s3.generate_presigned_url(
                    "get_object",
                    Params={"Bucket": _s.S3_BUCKET, "Key": s3_key},
                    ExpiresIn=900,
                )
            if _s.S3_PUBLIC_ENDPOINT_URL and _s.S3_ENDPOINT_URL in url:
                url = url.replace(_s.S3_ENDPOINT_URL, _s.S3_PUBLIC_ENDPOINT_URL, 1)
            return {"slug": slug, "file_url": url}
        except Exception as exc:
            raise HTTPException(status_code=500, detail=f"Failed to generate download URL: {exc}")

    raise HTTPException(status_code=404, detail=f"Dataset '{slug}' has no content yet")


@router.get("/models")
async def list_models(key=Depends(_require_api_key)):
    """List trained models available to this org."""
    from app.models.trainer_registration import TrainerRegistration
    org_id = key.org_id
    query: Dict[str, Any] = {"approval_status": "approved", "is_active": True}
    if org_id:
        query["$or"] = [{"org_id": org_id}, {"org_id": None}]  # own + system models
    regs = await TrainerRegistration.find(query).to_list()
    return [
        {
            "name": r.name,
            "version": getattr(r, "version_num", 1),
            "description": getattr(r, "description", ""),
            "task": getattr(r, "task_type", ""),
        }
        for r in regs
    ]


class InferenceRequest(BaseModel):
    inputs: Dict[str, Any]
    version: Optional[str] = None


@router.post("/inference/{trainer_name}")
async def run_inference(
    trainer_name: str,
    body: InferenceRequest,
    key=Depends(_require_api_key),
):
    """
    Run inference on a trained model.
    Returns the same dict that trainer.predict() returns.
    """
    from app.services.registry_service import get_trainer_class
    from app.services.inference_service import run_predict

    org_id = key.org_id
    cls = get_trainer_class(trainer_name)
    if not cls:
        raise HTTPException(status_code=404, detail=f"Model '{trainer_name}' not found or not deployed")

    try:
        result = await run_predict(trainer_name, body.inputs, org_id=org_id or "")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    return {"trainer": trainer_name, "result": result}
