#!/usr/bin/env python3
"""
Sandbox entrypoint — runs INSIDE the isolated Docker container.

This script has:
  - No app source code
  - No infrastructure credentials
  - No network access (--network=none)
  - Read-only filesystem except /sandbox_workspace and /tmp

Receives from the orchestrator (via shared volume):
  /sandbox_workspace/{job_id}/trainer.py          — user-uploaded trainer
  /sandbox_workspace/{job_id}/input/data.pkl      — serialized training data (train mode)
  /sandbox_workspace/{job_id}/input/model.pkl     — serialized model (predict mode)
  /sandbox_workspace/{job_id}/input/config.json   — training config scalars
  /sandbox_workspace/{job_id}/input/inputs.json   — inference inputs (predict mode)

Writes results to:
  /sandbox_workspace/{job_id}/output/model.pkl    — trained model (train mode)
  /sandbox_workspace/{job_id}/output/result.json  — metrics / prediction / error
"""
from __future__ import annotations

import importlib.util
import json
import os
import sys
import traceback
import types
from pathlib import Path
from types import SimpleNamespace

# ── Shim: provide app.abstract.base_trainer so trainers that import it work ───
# Trainers generated by the AI editor may do `from app.abstract.base_trainer import BaseTrainer`.
# We inject a minimal stub so the import doesn't fail.

def _inject_base_trainer_shim() -> None:
    class _BaseTrainer:
        pass

    class _TrainingConfig:
        def __init__(self, **kwargs: object) -> None:
            for k, v in kwargs.items():
                setattr(self, k, v)

    class _OutputFieldSpec:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

    class _TrainerBundle:
        def __init__(self, model: object = None, extra: dict | None = None) -> None:
            self.model = model
            self.extra = extra or {}

    bt_mod = types.ModuleType("app.abstract.base_trainer")
    bt_mod.BaseTrainer    = _BaseTrainer        # type: ignore[attr-defined]
    bt_mod.TrainingConfig = _TrainingConfig     # type: ignore[attr-defined]
    bt_mod.OutputFieldSpec = _OutputFieldSpec   # type: ignore[attr-defined]
    bt_mod.TrainerBundle  = _TrainerBundle      # type: ignore[attr-defined]

    app_mod      = types.ModuleType("app")
    abstract_mod = types.ModuleType("app.abstract")

    sys.modules.setdefault("app", app_mod)
    sys.modules.setdefault("app.abstract", abstract_mod)
    sys.modules["app.abstract.base_trainer"] = bt_mod


_inject_base_trainer_shim()

# ── Serialization — prefer cloudpickle, fall back to stdlib pickle ─────────────

try:
    import cloudpickle as _pkl
except ImportError:
    import pickle as _pkl  # type: ignore[no-redef]


# ── Helpers ───────────────────────────────────────────────────────────────────

def _load_trainer(trainer_path: Path) -> object:
    spec = importlib.util.spec_from_file_location("_sandbox_trainer", trainer_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load trainer from {trainer_path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]

    # Find the first class that looks like a trainer
    for name in dir(mod):
        if name.startswith("_"):
            continue
        obj = getattr(mod, name)
        if isinstance(obj, type) and (hasattr(obj, "train") or hasattr(obj, "predict")):
            return obj()
    raise RuntimeError("No trainer class found in trainer.py (needs train() or predict())")


def _to_json_safe(obj: object) -> object:
    """Recursively make an object JSON-serialisable."""
    if isinstance(obj, (str, int, float, bool, type(None))):
        return obj
    if isinstance(obj, dict):
        return {str(k): _to_json_safe(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_to_json_safe(v) for v in obj]
    try:
        import numpy as np  # type: ignore[import]
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
    except ImportError:
        pass
    return str(obj)


# ── Modes ─────────────────────────────────────────────────────────────────────

def _run_train(base: Path) -> None:
    with open(base / "input" / "data.pkl", "rb") as f:
        raw_data = _pkl.load(f)

    with open(base / "input" / "config.json") as f:
        config_dict = json.load(f)

    config = SimpleNamespace(**config_dict)
    trainer = _load_trainer(base / "trainer.py")

    preprocessed = trainer.preprocess(raw_data)
    result = trainer.train(preprocessed, config)

    model = result
    test_data = None
    if isinstance(result, tuple) and len(result) == 2:
        model, test_data = result

    metrics: dict = {}
    if test_data is not None:
        try:
            eval_result = trainer.evaluate(model, test_data)
            if isinstance(eval_result, dict):
                metrics = eval_result
            elif hasattr(eval_result, "__dict__"):
                metrics = {
                    k: v for k, v in vars(eval_result).items()
                    if isinstance(v, (int, float, str, bool))
                }
        except NotImplementedError:
            pass
        except Exception as exc:
            metrics = {"eval_error": str(exc)}

    out = base / "output"
    out.mkdir(parents=True, exist_ok=True)

    with open(out / "model.pkl", "wb") as f:
        _pkl.dump(model, f)

    with open(out / "result.json", "w") as f:
        json.dump({"status": "ok", "metrics": _to_json_safe(metrics)}, f)


def _run_predict(base: Path) -> None:
    with open(base / "input" / "model.pkl", "rb") as f:
        model = _pkl.load(f)

    with open(base / "input" / "inputs.json") as f:
        inputs = json.load(f)

    trainer = _load_trainer(base / "trainer.py")
    result  = trainer.predict(model, inputs)

    out = base / "output"
    out.mkdir(parents=True, exist_ok=True)

    with open(out / "result.json", "w") as f:
        json.dump({"status": "ok", "result": _to_json_safe(result)}, f)


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    job_id = os.environ.get("SANDBOX_JOB_ID")
    mode   = os.environ.get("SANDBOX_MODE", "train")

    if not job_id:
        print("SANDBOX_JOB_ID not set", file=sys.stderr)
        sys.exit(1)

    base = Path("/sandbox_workspace") / job_id

    if mode == "train":
        _run_train(base)
    elif mode == "predict":
        _run_predict(base)
    else:
        raise ValueError(f"Unknown SANDBOX_MODE: {mode}")


if __name__ == "__main__":
    job_id = os.environ.get("SANDBOX_JOB_ID", "unknown")
    base   = Path("/sandbox_workspace") / job_id
    try:
        main()
    except Exception as exc:
        tb = traceback.format_exc()
        print(tb, file=sys.stderr)
        out = base / "output"
        out.mkdir(parents=True, exist_ok=True)
        with open(out / "result.json", "w") as f:
            json.dump({"status": "error", "error": str(exc), "traceback": tb}, f)
        sys.exit(1)
